# Doris FE 配置文件

# 元数据目录
meta_dir = /opt/apache-doris/fe/doris-meta

# 网络配置
priority_networks = 172.20.0.0/16

# 日志配置
sys_log_level = INFO
sys_log_dir = /opt/apache-doris/fe/log
sys_log_roll_num = 10
sys_log_roll_size_mb = 1024
sys_log_verbose_modules = org.apache.doris

# JVM配置
JAVA_OPTS = "-Xmx2048m -XX:+UseMembar -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 -Xloggc:$DORIS_HOME/log/fe.gc.log"

# 查询端口
query_port = 9030
# RPC端口
rpc_port = 9020
# HTTP端口
http_port = 8030

# 前端节点配置
frontend_address = doris-fe
