# Doris BE 配置文件

# 存储目录
storage_root_path = /opt/apache-doris/be/storage

# 网络配置
priority_networks = 172.20.0.0/16

# 日志配置
sys_log_level = INFO
sys_log_dir = /opt/apache-doris/be/log
sys_log_roll_num = 10
sys_log_roll_size_mb = 1024
sys_log_verbose_modules = org.apache.doris

# JVM配置
JAVA_OPTS = "-Xmx4096m -XX:+UseMembar -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 -Xloggc:$DORIS_HOME/log/be.gc.log"

# 查询端口
be_port = 9060
# Web端口
webserver_port = 8040
# Heartbeat端口
heartbeat_service_port = 9050
# BRPC端口
brpc_port = 8060

# 前端节点地址
frontend_address = doris-fe:9010
